onnx/onnx-tensorflow

onnx_tf/backend.py, test/backend/test_node.py
As Cast test cases added to ONNX, https://github.com/onnx/onnx/blob/master/docs/Operators.md#Cast
Unlike key in there case is uppercase, onnx-tensorflow's is lowercase.
Convert to lowercase to get dtype in backend.
=> use lower case to get dtype

onnx_tf/backend.py, onnx_tf/common.py, onnx_tf/frontend.py
#47 
I've removed "seed": "seed2" attr map because I find `tf.random_normal`, `tf.random_uniform` is using `seed` instead of `seed2`.
So I suppose we don't need this attr map anymore.
Also I've moved "to": "dtype" attr map which is only for `Cast` op to per op one.
=> Remove duplicate source

onnx_tf/doc/API.md, onnx_tf/frontend.py
Frontend API for now is too verbose mainly because we have to find the output node oursevles. 
Currently we have:
```
def get_node_by_name(nodes, name):
for node in nodes:
if node.name == name:
return node
with tf.gfile.GFile(graph_pb, "rb") as f:
graph_def = tf.GraphDef()
graph_def.ParseFromString(f.read())
onnx_model = tensorflow_graph_to_onnx_model(graph_def,
get_node_by_name(graph_def.node, "fc2/add"),
opset=6,
producer_name="onnx-tensorflow",
graph_name="graph")
```
Proposing to change to 
```
onnx_model = tensorflow_graph_to_onnx_model(graph_def,
"fc2/add",
opset=6,
producer_name="onnx-tensorflow",
graph_name="graph")
```
=> fix frontend API verbosity

onnx_tf/__init__.py, setup.py
the wheel package of onnx-tensorflow 1.0 doesn't include `.py` files under `frontends` directory and `backends` directory. (Actually, directories themselves didn't exist.)
This PR fix the issue. In addition, this PR also adds some `import` statement in `onnx_tf/__init__.py`.
The latter change was needed to make it work on my environment. (Python: 3.6.3 with pyenv, OS: ubunu 16.04.)
=> enable import onnx_tf.frontend/backend from the outside of repository

README.md, setup.py
@tjingrant 
I know we need tensorflow to do both backend and frontend.
But in practice, not only tensorflow, tensorflow-gpu is also used widely. 
(Actually it's my case) I have to switch environment to do convert.
I think remove them from setup.py and let user install deps by themselves is a better idea.
numpy problem is fixed so remove it also.
What do you think?
=> remove requires of tensorflow and numpy in setup.py

onnx_tf/frontend.py, onnx_tf/frontends/frontend_v1.py, test/frontend/test_node.py
Introduce data type caster in frontend.
Mainly used for casting data type which is different from tf.
For example, [`Tile`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#tile) has type `int64` for `repeats` which could be `int32`, `int64` in [tf](https://www.tensorflow.org/api_docs/python/tf/tile).
=> introduce data type caster

MANIFEST.in
Without this, the package isn't installable from pip. For example, [this build](https://circleci.com/gh/conda-forge/onnx-tf-feedstock/58?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), which is basically equivalent to this:
```
$ conda create -n tmp -c conda-forge onnx
[...]
$ conda activate tmp
$ pip install onnx-tf
Collecting onnx-tf
Downloading https://files.pythonhosted.org/packages/d1/20/544cec0c523e68eed30f3990a70897c43ef326407189f43c0f4fbb9f32b2/onnx-tf-1.1.1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-owqdmri1/onnx-tf/setup.py", line 6, in <module>
with open(os.path.join(TOP_DIR, 'VERSION_NUMBER')) as version_file:
FileNotFoundError: …
```
=> include VERSION_NUMBER, ONNX_VERSION_NUMBER in pypi distribution

onnx_tf/common/__init__.py, onnx_tf/handlers/backend/batch_normalization.py, test/backend/test_node.py
As they changed the specification of bn from v7, the test mode is always used in bn.
~~I am not sure with if `"PYTEST_CURRENT_TEST" in os.environ` is OK for local test~~
=> force to use test mode in bn v7

doc/support_status.md, onnx_tf/handlers/backend/image_scaler.py, onnx_tf/opset_version.py, test/backend/test_node.py
Scale and bias the input image.
In the onnx difinition:
* Input tensor has shape [N,C,H,W].
* Output has same shape and type as input.
* Bias applied to each channel, same size as C.
=> add imagescaler support to backend

onnx_tf/backend.py
c.f. https://github.com/onnx/onnx/issues/1403, https://github.com/onnx/onnx-tensorflow/issues/244
This PR deals with an unspecified behavior in ONNX spec.
The motivation for this fix is that it allows our users to go through the tutorial smoothly; the tutorial happens to use a very outdated onnx model that reveals the loophole in the spec.
Basically, when ir_version < 3, opset_import is not specified, which means we automatically import the highest opset_version, causing breakage to outdated models. ONNX spec does not specify behaviors of backend in such situations, but friends from the spec repository suggest defaulting opset_import to 1 is a good idea.
=> Change onnx-tf behavior regarding a corner case ONNX spec does not address

onnx_tf/handlers/frontend/bias_add.py, test/frontend/test_node.py
In bias_add, the channel first check doesn't work in
python3, and inputs outputs name mismatch causes
disconnected nodes in graph. Add type check for
data_format[1] and underscore for inputs.
=> Fix python3 issue and disconnected nodes

setup.py, test/frontend/test_model.py, test/frontend/test_model.yaml
Added end-to-end model level testing from
1. TF checkpoint/graph freezing.
2. Get reference tf output results (X, Y).
3. Export to onnx via onnx-tf.
4. Load the onnx model using onnx-tf backend.
5. Run reference input X, get Y'.
6. Check equivalence of (Y, Y').
Should be comprehensive/sufficient enough to ensure success of exporting.
=> Frontend model test

onnx_tf/common/handler_helper.py
This is a warning message. It should use "warnings.warn" instead of "print" to display this message.
=> Change a debug "error" message to warning message

README.md
On my (relatively standard) desktop, the test suite takes 938 seconds, and downloads several very large neural networks. There should be a warning here for this for obvious reasons including hard disk space and network connectivity. Feel free to reject or modify the PR to make the warning more explicit. Thanks!
=> Updated readme to contain warning for testing

onnx_tf/common/handler_helper.py, onnx_tf/gen_opset.py, onnx_tf/opr_checker.py
The graph check cli is broken with the addition of
experimental ops returned from get_frontend_coverage.
Also fixed the logging not working issue because of
earlier logging level set to warning.
=> Fix check cli

doc/support_status.md, onnx_tf/handlers/backend/where.py, onnx_tf/handlers/frontend/select.py, onnx_tf/opset_version.py, test/backend/test_node.py, test/frontend/test_node.py
Add frontend and backend support for Where operator which was
introduced in ONNX opset version 9.
Also filter out ConstantFill test cases since the operator
is removed from ONNX.
=> Add frontend and backend support for Where

onnx_tf/handlers/backend/shrink.py, onnx_tf/opset_version.py, test/backend/test_node.py
Add backend support for Shrink which is introduced in
ONNX opset version 9.
There is no matching Tensorflow operator for shrink.
So the backend handler doesn't have tf.func decorator
and there is no frontend handler.
=> Add backend support for Shrink

doc/support_status.md, onnx_tf/handlers/backend/lstm.py
Fix the lstm issue with no initial_c, getting the
wrong result, as describled in issue:
https://github.com/onnx/onnx-tensorflow/issues/408
The solution is to set initial_c as zero when not provided
as an input, following onnx's assumption.
=> Fix the lstm issue with no initial_c

onnx_tf/handlers/backend/onehot.py, onnx_tf/handlers/frontend/onehot.py, test/backend/test_onnx_backend.py
Add args_check() in the handler to detect the unsupported dtype for indices & depth
Skip the ONNX unit test that are using the unsupported dtype
=> Check unsupported dtype for OneHot

.travis.yml, .travis/setup.sh, test/backend/test_node.py
Made a few minor updates
1. add python version check to run different pythons in docker
2. change base OS to xenial
3. remove script for release tag so we simply run CI for master
=> Update CI to use proper python versions

.travis/onnx-master_tf-nightly/Dockerfile, doc/support_status.md, onnx_tf/handlers/backend/dropout.py, onnx_tf/opset_version.py, test/backend/test_node.py
Add opset 10 support for dropout and update CI environment to use TensorFlow stable release instead of nightly build
=> Add opset 10 support for dropout

onnx_tf/backend_rep.py
TF output nodes should have the same output_names as the onnx model.
=> Give meaningful name to the output tf nodes.

.travis.yml, .travis/onnx-master_tf-1.x-release/Dockerfile, .travis/setup_onnx_master.sh, .travis/setup_onnx_target.sh, README.md, onnx_tf/handlers/backend/gather_and_scatter_mixin.py, onnx_tf/handlers/backend/gather_nd.py, onnx_tf/handlers/backend/scatter_elements.py, onnx_tf/handlers/backend/scatter_nd.py, onnx_tf/handlers/backend/slice.py, test/backend/test_node.py, test/backend/test_onnx_backend.py
Add support for negative indices and check indices out of bounds in GatherND, ScatterND and ScatterElements
Change the implementation of negative support of axes in Slice 
Improve the rule for skipping some ONNX backend test temporary in test_onnx_backend.py
Update README.md to reflect this README file is only for tf-1.x
=> Extend support for GatherND/ScatterND/ScatterElements

onnx_tf/handlers/backend/split.py, test/backend/test_node.py
Add opset 11 support for Split in checking the axis to be
inbound and providing a test case.
=> Add opset 11 support for Split

onnx_tf/backend.py
When a ONNX graph is converted, the initialization constant tensor names are not preserved in the target tensorflow model. Preserving constant names should improve quality of the converted model.
https://github.com/onnx/onnx-tensorflow/issues/545
=> preserve names of initial tensor constants

onnx_tf/backend.py
Apply the change in https://github.com/onnx/onnx-tensorflow/pull/544 to tf-1.x branch
=> tf-1.x: preserve names of initial tensor constants

onnx_tf/handlers/backend/equal.py
`from onnx_tf.common import exception` for access to `exception.OP_UNSUPPORTED_EXCEPT` on line 29
=> Undefined name from onnx_tf.common import exception

doc/support_status.md, onnx_tf/backend.py, onnx_tf/handlers/backend/if.py, onnx_tf/handlers/backend/loop.py, onnx_tf/handlers/backend/scan_mixin.py, onnx_tf/opset_version.py, test/backend/test_node.py, test/backend/test_onnx_backend.py
1. add opset 11 support for If
2. update onnx_graph_to_tensorflow_ops to get initializer nodes values from tensor_dict of the whole graph for the subgraph in Loop, Scan and If operators
3. fix the optional input handle in loop handler and update test_loop in test_node.py to reflect the change
4. skip CumSum onnx backend test because axis in the testcases are not created with correct shape
=> Add opset 11 support for If

doc/support_status.md, onnx_tf/handlers/backend/non_max_suppression.py
Input max_output_boxes_per_class, iou_threshold and score_threshold
should all be scalar, but the handler will accept 1-D 1 element tensor
as the value and squeeze out the extra dimension.
(The unit tests in ONNX backend test are using 1-D 1 element tensor for 
max_output_boxes_per_class, iou_threshold and score_threshold however, 
in model like Tiny YOLOv3 use scalar for those inputs.)
=> Fix NonMaxSuppression handler

onnx_tf/handlers/backend/conv_integer.py, test/backend/test_node.py
'x_zero_point' and 'w_zero_point' are both optional inputs, should check the number of inputs to decide whether the user have send in these optional inputs, and should get the value by the input position.
=> Fix ConvInteger optional inputs handle

onnx_tf/handlers/backend_handler.py
Sometimes `inputs` passed to `BackendHandler._run_tf_func` may have so many elements that they intersect with given `attrs`. It causes errors like ones mentioned there: https://github.com/onnx/onnx-tensorflow/issues/499#issuecomment-623029133. I suggest to check such ambiguities and allow passing them if one of the passed values is `None`.
=> Fix TF func call with duplicate arguments

onnx_tf/handlers/backend/sequence_erase.py
"position" is an optional input and the default value should be set to the position of the last tensor in the sequence.
=> Fix SequenceErase optional input handle

onnx_tf/handlers/backend/slice.py
----
When running the backend tests, I noticed `test_slice_default_axes_cpu` was failing with this error:
```
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: <tf.Tensor 'strided_slice:0' shape=() dtype=int32>
```
The call to `tf.shape(starts)` was returning `int32` which caused the surrounding call to `tf.range()` to fail. Using `tf.shape(starts, out_type=ends.dtype)` similar to line 60 puts the type casting into the correct location.
=> Fix shape dtype in Slice when using default axes (tf-1.x)

onnx_tf/handlers/backend/expand.py, test/backend/test_node.py
If the input data type is bool, the expand operator would
fail to convert and throw an exception, as described in
https://github.com/onnx/onnx-tensorflow/issues/600
This PR converts input data to tf.int32 for matmul when
dtype is bool.
=> Fix an expand issue with bool

onnx_tf/common/pooling_helper.py, test/backend/test_node.py
---
This fixes a test failure in the backend tests. Steps to recreate:
1. Regenerate the ONNX backend test data with `backend-test-tools generate-data`. Not clear on why the error does not occur before regenerating the test data.
2. Run the ONNX-TF backend tests with `pytest -v -s -k 'not _cuda' test/backend/test_onnx_backend.py`
Error reported:
```
test/backend/test_onnx_backend.py::OnnxBackendNodeModelTest::test_averagepool_2d_same_lower_cpu 2020-06-16 16:05:46.684938: W tensorflow/core/framework/op_kernel.cc:1639] Invalid argument: TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Traceback (most recent call last):
File "/Users/pluradj/anaconda3/envs/onnx-tf1-dev/lib/python3.7/site-packages/tensorflow_core/python/ …
```
=> Fix pooling string comparison and case for auto_pad (tf-1.x)

onnx_tf/handlers/backend/reshape.py, onnx_tf/handlers/backend/slice.py, test/backend/test_node.py
This PR fixes the deprecated tf.compat.v1.sparse_to_dense API with
tf.sparse.SparseTensor and tf.sparse.to_dense
=> Fix deprecated sparse_to_dense API

doc/support_status.md, onnx_tf/handlers/backend/gather_elements.py, onnx_tf/opset_version.py, test/backend/test_node.py
---
* Tests added to `test_node.py`
* Verified `GatherElements` backend tests pass (3) with `test/backend/test_onnx_backend.py`
* Ran `yapf` against `onnx_tf/opset_version.py` so there is some additional reformatting in that file
=> Add opset 11 support for GatherElements

onnx_tf/backend.py
Node name cannot start with an underscore character in Tensorflow.
This PR prepends a unique string to make it unique and valid.
=> Fix initializer node name with leading underscore character

onnx_tf/handlers/backend/sequence_at.py, onnx_tf/handlers/backend/sequence_erase.py, onnx_tf/handlers/backend/sequence_insert.py, onnx_tf/handlers/backend/sequence_length.py
This PR fixes a couple of dtype issues in the sequence ops:
1. The output dtype should be int64 for SequenceLength
2. The position check casts to int32 when postion could be either
int32 or int64
=> Fix dtype issues in sequence operators

doc/support_status.md, onnx_tf/common/pooling_helper.py, onnx_tf/handlers/backend/clip.py, onnx_tf/handlers/backend/dilated_pooling.py, onnx_tf/handlers/backend/lp_pool.py, onnx_tf/handlers/backend/pool_mixin.py, onnx_tf/opset_version.py, test/backend/test_node.py
Implements LpPool by utilizing avg_pool:
window_size = np.prod(ksize)
input = tf.math.pow(input, self.p) * window_size
pooled = tf.nn.avg_pool(input, ksize=ksize, strides=strides, padding=padding)
pooled = tf.math.pow(pooled, 1.0 / self.p)
=> LpPool operator implementation

doc/support_status.md, onnx_tf/common/data_type.py, onnx_tf/handlers/backend/arg_max.py, onnx_tf/handlers/backend/arg_min.py, onnx_tf/handlers/backend/cast.py, onnx_tf/opset_version.py, test/backend/test_model.py, test/backend/test_node.py
The change in Opset 13 was a Type Constraint to support tensor(bfloat16). I have added test for this.
=> Added Opset 13 support for ArgMax and ArgMin

.gitignore, doc/support_status.md, onnx_tf/common/__init__.py, onnx_tf/common/data_type.py, onnx_tf/handlers/backend/pow.py, onnx_tf/opset_version.py, test/backend/test_model.py
Add Pow support for opset 12 and 13 including
1. add data type cast whenever needed
2. add support when input and exponent have different types
3. add test case for bfloat16 in test_model.py
Also updated .gitignore so the generated version.py is not
tracked by git
=> Add Pow support for opset 12 and 13

onnx_tf/handlers/backend_handler.py
Backport duplicate argument name fix, PR 650, into
tf-1.x branch
=> Backport duplicate argument name fix into tf-1.x

doc/support_status.md, onnx_tf/handlers/backend/sequence_at.py, onnx_tf/handlers/backend/sequence_construct.py, onnx_tf/handlers/backend/sequence_empty.py, onnx_tf/handlers/backend/sequence_erase.py, onnx_tf/handlers/backend/sequence_insert.py, onnx_tf/handlers/backend/sequence_length.py, onnx_tf/opset_version.py, test/backend/test_model.py
Add sequence ops support for opset 11 to tf-1.x branch. The same
implementation can found in PR https://github.com/onnx/onnx-tensorflow/pull/560
=> Add sequence ops support for opset 11 to tf-1.x

doc/API.md, doc/CLI.md, doc/support_status.md, onnx_tf/backend.py, onnx_tf/common/data_type.py, onnx_tf/common/exception.py, onnx_tf/converter.py, onnx_tf/handlers/backend/cumsum.py, onnx_tf/handlers/backend/equal.py, onnx_tf/handlers/backend/pow.py, onnx_tf/opset_version.py, test/backend/test_node.py, test/backend/test_onnx_backend.py
Add auto data type cast to support the data types that are
not natively supported by Tensorflow.
This PR adds the following
1. a common sys_config so the auto_cast option can be accessed
everywhere
2. additional data type support for equal operator
3. additional data type support for cumsum operator
4. unit tests for these data types
5. a new parameter auto-cast for CLI and prepare
=> Add auto data type cast

doc/support_status.md, onnx_tf/handlers/backend/dropout.py, onnx_tf/opset_version.py, test/backend/test_node.py, test/backend/test_onnx_backend.py
As of Opset 12, the Dropout operator now supports training mode. I have created tests for this. The test is an average of 20 runs of the operator. It checks that the ratio of dropouts in the output is almost equal to the  ratio requested.
Opset 13 supports a bfloat16 input tensor. I have verified that tf.nn.dropout works fine with bfloat16 tensors. I have not created a test case for this.
This will close issue #552
=> Updated Dropout operator to support Opset 12 and 13.

test/backend/test_onnx_backend.py
Add a filter to skip a few onnx backend tests for
lstm, gru, and rnn. Tensorflow doesn't work well with
custom variables and tf.module together. Need more
investigation to provide a solution.
=> Fix CI for lstm, gru, and rnn tests

example/test_mnist_onnxruntime_stepping.py, onnx_tf/backend.py, onnx_tf/backend_rep.py, onnx_tf/backend_tf_module.py
Add model stepping test for Mnist using ONNX runtime. The
assumption is that ONNX runtime is installed and the mnist model
from ONNX model zoo is downloaded.
=> Add model stepping test for Mnist

doc/support_status.md, onnx_tf/handlers/backend/clip.py, onnx_tf/handlers/backend/mod.py, onnx_tf/opset_version.py, test/backend/test_node.py
Add data cast support for Clip and Mod so that all ONNX data
types are supported for these two operators now.
Also add a test case in test_node.py for mod to verify data
cast working.
=> Add data cast support for Clip and Mod

doc/CLI.md, doc/support_status.md, onnx_tf/common/tf_helper.py, onnx_tf/converter.py, onnx_tf/handlers/backend/conv_mixin.py, test/backend/test_dynamic_shape.py
1. Add dynamic shape support for input x and w in conv_mixin.py
2. Fix issue #750
3. Update CLI.md
4. Update common.tf_helper to include dtype(int32/int64) as input
=> Dynamic shape support for ConvTranspose

doc/support_status.md, onnx_tf/handlers/backend/einsum.py, onnx_tf/opset_version.py, test/backend/test_node.py
1. Add opset 12 support for Einsum
2. Skip dropout, if and loop onnx-backend-test
3. Fix acosh, reduce_sum, split, squeeze and topk testcase in test_node.py
=> Add Einsum Opset 12 support

doc/CLI.md, doc/CLI_template.md, onnx_tf/backend.py, onnx_tf/backend_rep.py, onnx_tf/backend_tf_module.py, onnx_tf/handlers/backend/conv_mixin.py, onnx_tf/handlers/backend/dilated_pooling.py, onnx_tf/handlers/backend/non_max_suppression.py, onnx_tf/handlers/backend/random_normal_like.py, onnx_tf/handlers/backend_handler.py, test/backend/test_dynamic_shape.py
1. Add export_graph and use this graph to run in Tensorflow instead of using tf_rep.run for each dynamic shape testcases to verify our handlers can support unknown shape inputs.
2. Fix conv_mixin to support dynamic shape input for W.
3. Move tf.Variable creation into BackendTFModule.__init__ instead of creating them inside the handler.
4. Update non_max_suppression handler to create the tf.Variable in BackendTFModule.__init__ and use the variable in the handler
5. Fix random_normal_like handler to support dynamic shape input.
6. Fix dilated_pooling to handle unknown input shape.
7. Add ONNX operators count to tf_rep.
8. Minor update on CLI_template.md
=> Fix dynamic shape test and move handler's variable creation into BackendTFModule.__init__

doc/support_status.md, onnx_tf/handlers/backend/roi_align.py
Hi
This PR add RoiAlign support to tf-1.x.
`sampling_ratio`>0 part are fine. But I didn't manage to fully implement `sampling_ratio`<=0 case with python only.
The results of `sampling_ratio`<=0 might be **flatten** than other implementation(onnxruntime/pytorch)
=> Add RoiAlign support

onnx_tf/handlers/backend/lstm.py, test/backend/test_model.py, test/backend/test_onnx_backend.py
Fix lstm export to saved model issue due to the use of
tf.Variable in the handler. Also add a test case to
test_model.py to verify a model can be exported and loaded
back successfully.
=> Fix lstm export to saved model issue

onnx_tf/common/legacy.py
Add support for ONNX release candidates which might have 'rc'
in release number, such as 1.8.0rc
=> Add support for ONNX release candidates

doc/support_status.md, onnx_tf/handlers/backend/hardmax.py, onnx_tf/opset_version.py, test/backend/test_node.py
The only change from opset 11 to 13 was support bfloat16 and also the default for axis is -1 in opset 13 as opposed to 1 in opset 11.
It appears that the implementation of converting to a 2d, doing a hardmax, and reshaping the
result did not really work. I  have changed the implementation to be transpose based and I
flip the result.
All tests pass.
Signed-off-by: Shahir A. Daya <sdaya@ca.ibm.com>
=> Updated Hardmax for opset 13 

onnx_tf/handlers/backend/gru.py, onnx_tf/handlers/backend/rnn.py, test/backend/test_model.py, test/backend/test_onnx_backend.py
Fix gru and rnn export issues by moving tf.Varable out of handler.
Also add test cases in test_model.py to export and load the saved
model before running the model.
=> Fix gru and rnn export issues

onnx_tf/handlers/backend/cumsum.py, onnx_tf/handlers/backend/equal.py, onnx_tf/handlers/backend/min.py, onnx_tf/handlers/backend/mod.py, onnx_tf/handlers/backend/pow.py, onnx_tf/handlers/backend/resize.py, test/backend/test_model.py
Fix auto cast for data type downcast by moving the auto-cast
check to args_check. Also add a simple test to verify the user
argument is applied for downcast when needed.
=> Fix auto cast for data type downcast

doc/support_status.md, onnx_tf/handlers/backend/onehot.py, onnx_tf/handlers/backend/roi_align.py, onnx_tf/opset_version.py, test/backend/test_node.py, test/backend/test_onnx_backend.py
1. Add auto-cast capability for input depth in OneHot handler
2. Update support_status for RoiAlign support
=> Add auto-cast capability into OneHot handler

doc/support_status.md, onnx_tf/handlers/backend/clip.py, onnx_tf/handlers/backend/mod.py, onnx_tf/opset_version.py, test/backend/test_node.py
Backport data type support for clip and mod using the
auto-cast feature and add a test cast in test_node.py.
=> Backport data type support for clip and mod

onnx_tf/common/data_type.py, onnx_tf/handlers/backend/cumsum.py, onnx_tf/handlers/backend/equal.py, onnx_tf/handlers/backend_handler.py, test/backend/test_node.py
This backport PR includes
1. data type cast support for cumsum (#706)
2. data type cast support for equal (#706)
3. unit tests for cumsum and equal (#706)
4. attribute name fix (#348)
5. bfloat16 support (#706)
=> Backport cumsum, equal support, attribute name fix

onnx_tf/handlers/backend/onehot.py, test/backend/test_node.py, test/backend/test_onnx_backend.py
cast "indices" base on auto-cast option instead of always cast to int64
=> Minor change in Onehot auto-cast support

onnx_tf/handlers/backend/slice.py
Fix Slice version 1 to support model zoo models:
age_gender, version-RFB-320.onnx
age_gender, version-RFB-640.onnx
=> Fix Slice version 1 to support model zoo models

onnx_tf/handlers/backend/less_or_equal.py, test/backend/test_node.py
Add data cast to fix LessOrEqual issue with tf 2.4, since
tf LessEqual doesn't support uint16, uint32, uint64. Also
add test code to verify unsupported data types.
=> Add data cast to fix LessOrEqual issue with tf 2.4

example/train_onnx_model.py, onnx_tf/backend.py, onnx_tf/handlers/backend/broadcast_mixin.py
1. Update backend.prepare() to generate tf_rep for model training: generate tensor_dict and graph only in training mode. 
2. Add an example to train a onnx model : example/train_onnx_model.py
3. Batchnomalization OP for training model is not supported so far.
=> Support train onnx model with tensorflow

doc/support_status.md, onnx_tf/handlers/backend/identity.py, onnx_tf/opset_version.py, test/backend/test_onnx_backend.py
Fix Identity with sequence type with two workarounds since
Tensorflow Identity doesn't support sequence:
1. update identity handler as partial support
2. skip the standard ONNX test case for identity with sequence
=> Fix Identity with sequence type

onnx_tf/handlers/backend/pad.py, onnx_tf/opset_version.py, test/backend/test_node.py
Add new data types support for Pad, which gets
string, bool, and bfloat16. Also add a test case
for string type.
=> Add new data types support for Pad

onnx_tf/handlers/backend/div.py
Fix Div to return the original data types when the inputs are
integers. In such case, Tensorflow automatically casts inputs to
a float type and returns in floating point in tf.math.truediv. So
we need to handle these integral data types propertly.
=> Fix Div to return the original data types

onnx_tf/handlers/backend/depth_to_space.py, test/backend/test_dynamic_shape.py
Nets using DepthToSpace are currently incompatible with dynamic axes. It's enough to switch from `x.shape` to `tf.shape(x)` along with manual unrolling of the resulting 4-dimensional tensor (as one is not allowed to directly iterate over a tf.Tensor).
Related to [#543](https://github.com/onnx/onnx-tensorflow/pull/543) and [#771](https://github.com/onnx/onnx-tensorflow/pull/771)
Edit: Added a unittest. It's my first one and my second PR ever, so fingers crossed..!
=> fix dynamic shape inference in DepthToSpace

onnx_tf/handlers/backend/instance_normalization.py
Fix InstanceNormalization unknown channel size issue where the
reshape will fail due to unknown size. The scale shape will be
used in this case now.
This patch should fix https://github.com/onnx/onnx-tensorflow/issues/886
=> Fix InstanceNormalization unknown channel size issue

onnx_tf/handlers/backend/slice.py
The len() method was used on a tensor's shpae, which is no longer legal in TF2.
=> Fix a bug in slice operator

doc/CLI.md, onnx_tf/converter.py
Add suppor for ONNX model with external data with a new optional
command line argument to specify the external data directory.
=> Add suppor for ONNX model with external data

.github/workflows/test-backend.yml, doc/support_status.md, onnx_tf/handlers/backend/pow.py, onnx_tf/opset_version.py, test/backend/test_onnx_backend.py
Add support for Pow opset 15, where bfloat16 data type is added
Also add a filter in test_onnx_backend.py to exclude tests with
optional inputs.
=> Add support for Pow opset 15

onnx_tf/handlers/backend/resize.py
Fix resize for optional inputs in opset 13, more specifically
for roi and scales which could be empty strings as the input
name
=> Fix resize for optional inputs in opset 13

onnx_tf/handlers/backend/optional.py, test/backend/test_node.py
Return None for tensor type and return [] for sequence type.
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Optional
Optional
Constructs an optional-type value containing either an empty optional of a certain type specified by the attribute
Type Constraints
V : tensor(uint8), tensor(uint16), tensor(uint32), tensor(uint64), tensor(int8), tensor(int16), tensor(int32), tensor(int64), tensor(float16), tensor(float), tensor(double), tensor(string), tensor(bool), tensor(complex64), tensor(complex128), seq(tensor(uint8)), seq(tensor(uint16)), seq(tensor(uint32)), seq(tensor(uint64)), seq(tensor(int8)), seq(tensor(int16)), seq(tensor(int32)), seq(tensor(int64)), seq(tensor(float16)), seq(tensor(float)), seq(tensor(double)), …
=> update Optional operator to return right type value for empty value

.github/workflows/test-backend.yml, .github/workflows/test-modelzoo.yml, README.md, doc/support_status.md
Update Tensorflow and ONNX versions
tensorflow==2.8.0
tensorflow-addons==0.16.1
tensorflow-probability==0.16.0
onnx==1.10.2
=> Update Tensorflow (2.8.0) and ONNX (1.10.2) versions

onnx_tf/handlers/backend/split.py
Fix input rank unknown issue for split by checking the input
rank and skipping the validation when rank is unknown.
=> Fix input rank unknown issue for split

setup.py
Add `tensorflow_probability` to the `install_requires` list in `setup.py`, similarly to how we handle `tensorflow_addons`.
Fixes onnx/onnx-tensorflow#1015
=> Declare dependency on tensorflow_probability
