onnx/onnx-tensorflow

- onnx_tf/backend.py
- test/backend/test_node.py
https://github.com/onnx/onnx/pull/289
> ONNX has changed Pad operator attribute from 'paddings' to 'pads'

- .travis/build.sh
- onnx_tf/common.py
- onnx_tf/frontend.py
- test/frontend/test_node.py
There are several questions I'm currently still searching for answers to..
1. Best way to specify inputs/outputs. 
- Currently I take Placeholder node as an input.
- Currently I require the proto definition of output node to be passed in. 
2. Shape of output is not present in TF GraphDef.
I'll look into it more on Monday.
> initiating frontend dev

- onnx_tf/common.py
- onnx_tf/frontend.py
- test/frontend/test_node.py
*  Bug fix : give the real shape for Const node, not the flatten shape 
*  Add concat handler and test of concat in front-end 
*  Improve font end test_node
> Add concat handler in front-end

- test/frontend/test_node.py
> run tf.reset_default_graph at first in testing frontend.py

- onnx_tf/backend.py
- onnx_tf/frontend.py
- test/backend/test_node.py
- test/frontend/test_node.py
#53 
Finally, I fixed all build errors and passed the CI test.
But I am not sure if the fix is optimized.
And I added multiple outputs support.
> fix build failed and support multiple outputs

- onnx_tf/backend.py
I've added lstm handler. But without `reverse` direction support. I don't know how to do that. Any ideas?
> [WIP] add lstm handler

- onnx_tf/backend.py
- onnx_tf/common.py
- test/backend/test_node.py
- equal
- depth_to_space
- global_lp_pool
- less
- lp_normalization
> Support some ops

- README.md
- onnx_tf/backend.py
- onnx_tf/common.py
- test/backend/test_node.py
> support some ops and add default attr value injection

- onnx_tf/backend.py
- test/backend/test_node.py
> support some ops, add test cases and remove duplicate source

- onnx_tf/frontend.py
> remove consts/inputs after use them as attr in frontend

- onnx_tf/backend.py
- onnx_tf/common.py
- onnx_tf/frontend.py
- onnx_tf/gen_opset.py
In case that multiple tf ops match same onnx op.
> tiny refactoring

- example/test_model_large_stepping.py
- onnx_tf/backend.py
- onnx_tf/backend_rep.py
- onnx_tf/backends/backend_v1.py
- onnx_tf/backends/backend_v2.py
- onnx_tf/backends/backend_v3.py
- onnx_tf/backends/backend_v4.py
- onnx_tf/backends/backend_v5.py
- onnx_tf/backends/backend_v6.py
- onnx_tf/common.py
- onnx_tf/frontend.py
- onnx_tf/frontends/frontend_v1.py
- onnx_tf/frontends/frontend_v2.py
- onnx_tf/frontends/frontend_v3.py
- onnx_tf/frontends/frontend_v4.py
- onnx_tf/frontends/frontend_v5.py
- onnx_tf/gen_doc.py
- onnx_tf/gen_opset.py
- onnx_tf/opset_version.py
- onnx_tf/tf_net.py
- onnx_tf/third_party/get_info.py
- setup.py
- test/backend/test_model.py
- test/backend/test_node.py
- test/backend/test_onnx_backend.py
- test/frontend/test_node.py
#84 
Arguments: `-rip --style="{based_on_style: google, indent_width: 2}"`
> apply yapf

- onnx_tf/frontend.py
Need to use OperatorSetIdProto
> fix opset_imports can not be set properly bug

- test/backend/test_onnx_backend.py
https://github.com/onnx/onnx/pull/677
> remove code for skipping AvgPool test

- onnx_tf/doc/API.md
- onnx_tf/frontend.py
domain support does not in this PR. I think we should discuss more about it.
> Fix opset imports bug

- onnx_tf/backends/backend_v1.py
- onnx_tf/backends/backend_v2.py
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Split
> fix split of backend

- onnx_tf/frontend.py
Forget to set opset to latset.
> set default opset to latest

- onnx_tf/backend.py
- Add a condition to set shape with dim_value
- Set None when dim_param is not empty
> fix shape contains dim_param

- onnx_tf/backends/backend_v1.py
set default value 0. and remove cast if dtype is not set
> set default value to 0. for ConstantFill

- onnx_tf/backends/backend_v1.py
If None in x shape, np.min will crash.
> fix slice with None in shape

- example/test_model_large_stepping.py
- onnx_tf/frontend.py
- onnx_tf/frontends/frontend_v1.py
- test/backend/test_model.py
- test/backend/test_node.py
> remove onnx_pb2 from import

- onnx_tf/doc/IMPLEMENTING_NEW_OP.md
A brief doc for implementing new op.
> add doc for implementing new op

- onnx_tf/common.py
fix missing support of string.
> add string to ONNX_TYPE_TO_TF_TYPE

- onnx_tf/frontend.py
Preprocess graph_def to add infer_shapes to it anyway.
> add infer shapes to GraphDef

- onnx_tf/common/__init__.py
- onnx_tf/handlers/backend/dropout.py
> Fix dropout

- README.md
Furthermore, maybe we should add diff check after applying yapf into travis.
> add yapf to README.md

- doc/support_status.md
- onnx_tf/handlers/backend/dynamic_slice.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
Add DynmaicSlice handler to the backend. Also update
Less for version 9.
> Add DynamiceSlice backend support

- onnx_tf/handlers/backend/slice.py
- test/backend/test_node.py
Add support for slice negative starts, which is documented in ONNX
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Slice
Also add unit test for slice.
> Fix slice negative starts

- onnx_tf/common/attr_translator.py
- onnx_tf/common/data_type.py
> support multi dtypes

- doc/support_status.md
- onnx_tf/handlers/backend/eye_like.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
closes: https://github.com/onnx/onnx-tensorflow/issues/269
> Add EyeLike backend support

- doc/support_status.md
- onnx_tf/handlers/frontend/square.py
- onnx_tf/opset_version.py
- onnx_tf/pb_wrapper.py
- test/frontend/test_node.py
Add frontend support for tf.square by calling the existing Multiply frontend handler.
> Add frontend support for Square

- onnx_tf/handlers/frontend/size.py
Refactor size frontend handler to use TensorflowNode
instead of onnx helper make_node.
> Refactor size frontend handler

- doc/support_status.md
- onnx_tf/handlers/frontend/rsqrt.py
- onnx_tf/opset_version.py
- test/frontend/test_node.py
Add rsqrt frontend handler to support the rsqrt
operator in tf graph.
> Add rsqrt frontend support

- doc/support_status.md
- onnx_tf/handlers/frontend/floor_div.py
- onnx_tf/opset_version.py
- onnx_tf/pb_wrapper.py
- test/frontend/test_node.py
Add frontend support for tf.floordiv by calling the existing Div and Floor frontend handlers.
> Add floordiv frontend support

- test/backend/test_node.py
Fix a CI error for older versions of onnx and TF in the test code
for cast.
> Fix CI error for older versions of onnx and TF

- doc/support_status.md
- onnx_tf/handlers/backend/is_inf.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
Add  IsInf backend version 10 support
> Add IsInf backend

- onnx_tf/handlers/backend/slice.py
- test/backend/test_node.py
Fix the slice backend handler. The issue is due to a recent
change for opset 10 broke the opset 9 support.
> Fix slice backend handler

- doc/CLI.md
- doc/CLI_template.md
- test/backend/test_onnx_backend.py
- test/test_cli.py
Automatically skip the onnx unit tests of all not implemented operators in onnx-tf
> Skip test for all the not implemented operators 

- setup.py
To contain language check for py2 and py3.
> add classifiers section to the setup

- doc/IMPLEMENTING_NEW_OP.md
- doc/support_status.md
- onnx_tf/common/handler_helper.py
- onnx_tf/gen_doc.py
- onnx_tf/gen_opset.py
- onnx_tf/gen_status.py
- onnx_tf/handlers/backend/cast.py
- onnx_tf/handlers/backend/conv_transpose.py
- onnx_tf/handlers/backend/equal.py
- onnx_tf/handlers/backend/gru.py
- onnx_tf/handlers/backend/lstm.py
- onnx_tf/handlers/backend/max_pool.py
- onnx_tf/handlers/backend/mod.py
- onnx_tf/handlers/backend/onehot.py
- onnx_tf/handlers/backend/resize.py
- onnx_tf/handlers/backend/rnn.py
- onnx_tf/handlers/backend/rnn_mixin.py
- onnx_tf/handlers/backend/upsample.py
- onnx_tf/handlers/handler.py
- onnx_tf/opset_version.py
Update doc/support_status.md to new format
> Update support status report into new format

- doc/support_status.md
- onnx_tf/handlers/backend/mat_mul_integer.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
Add Opset 10 support for MatMulInteger
> Add support for MatMulInteger

- doc/support_status.md
- onnx_tf/handlers/backend/conv_integer.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
Add support for ConvInteger which is introduced since onnx
opset 10.
> Add support for ConvInteger

- doc/support_status.md
- onnx_tf/handlers/backend/conv_integer.py
- onnx_tf/handlers/backend/q_linear_conv.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
Add support for QLinearConv which is introduced in ONNX
opset 10.
> Add support for QLinearConv

- README.md
- onnx_tf/backend.py
- onnx_tf/handlers/backend/conv_mixin.py
- onnx_tf/handlers/backend/eye_like.py
- onnx_tf/handlers/backend/gather_and_scatter_mixin.py
- onnx_tf/handlers/backend/gather_nd.py
- onnx_tf/handlers/backend/is_inf.py
- onnx_tf/handlers/backend/scatter_nd.py
- test/backend/test_dynamic_shape.py
1. Add dynamic input support into handlers
2. Add unit test to verify dynamic shape support in handlers
> Verify EyeLike, Flatten, GatherND, IsInf and ScatterND can handle dynamic inputs

- onnx_tf/backend.py
- onnx_tf/handlers/backend/reshape.py
- onnx_tf/handlers/backend/slice.py
- test/backend/test_dynamic_shape.py
tf-1.x backport for https://github.com/onnx/onnx-tensorflow/pull/543
> Slice op dynamic shape tf1x

- onnx_tf/handlers/backend/compress.py
- test/backend/test_dynamic_shape.py
Update Compress handler to support dynamic shape
> Add dynamic input support for Compress

- onnx_tf/handlers/backend/split.py
- test/backend/test_node.py
Update Split handler and test code for opset 11.
Similar changes can be refereced at
https://github.com/onnx/onnx-tensorflow/pull/540
> Update Split for opset 11

- onnx_tf/handlers/backend/non_max_suppression.py
- test/backend/test_dynamic_shape.py
Update NonMaxSuppression handler to support dynamic shape
> Add dynamic input support for NonMaxSuppression

- onnx_tf/backend.py
- onnx_tf/common/__init__.py
- onnx_tf/common/data_type.py
- onnx_tf/common/exception.py
- onnx_tf/common/handler_helper.py
- onnx_tf/converter.py
- onnx_tf/handlers/backend/pool_mixin.py
- onnx_tf/handlers/backend/thresholded_relu.py
- onnx_tf/handlers/handler.py
- onnx_tf/pb_wrapper.py
This PR includes
1. add console handler with formatter to common logging
2. make use of common logging and console in places
we provide warning, info, and debug messages
3. change the logging level to info for since_version check
in hanlder helper because the severity is low
4. update convert and prepare to configure logging handler
> Use common logging console

- test/backend/test_node.py
Added convTranspose 1D and 2D tests. Tested on `device=cpu`
`Todo`: Add a test with strides > 1
> Added convTranspose 1D and 2D tests

- onnx_tf/handlers/backend/unpool_mixin.py
- test/backend/test_dynamic_shape.py
Added dynamic shape support for MaxUnpool op
> Dynamic shape support for MaxUnpool op

- doc/IMPLEMENTING_NEW_OP.md
- doc/support_status.md
- onnx_tf/handlers/backend/loop.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
- test/backend/test_onnx_backend.py
1. Add support for Loop operator
2. Removed some outdated instruction in IMPLEMENTING_NEW.OP.md
> Add opset 11 support for Loop

- doc/support_status.md
- onnx_tf/handlers/backend/arg_max.py
- onnx_tf/handlers/backend/arg_min.py
- onnx_tf/opset_version.py
- test/backend/test_dynamic_shape.py
- test/backend/test_node.py
> Added Opset 12 support for ArgMax and ArgMin to TF 1.x branch

- onnx_tf/handlers/backend/q_linear_conv.py
Bias must be quantized before added to the convolution
> Fix how QLinearConv apply bias

- onnx_tf/handlers/backend/clip.py
- onnx_tf/handlers/backend/q_linear_conv.py
- test/backend/test_node.py
1. Fix test_if in test_node.py to run on onnx 1.6
2. Check empty string for optional input name in Clip to fix onnx backend model test error
> Fix test_if in test_node.py to run on onnx 1.6

- onnx_tf/handlers/backend/mat_mul_integer.py
'a_zero_point' and 'b_zero_point' are both optional inputs, should check for empty input name and the number of inputs to decide whether the user have send in these optional inputs, and should get the value by the input position.
> Fix MatMulInteger optional inputs handle

- doc/support_status.md
- onnx_tf/handlers/backend/split.py
- onnx_tf/opset_version.py
1. Fix error report in issue #656 for Split
2. Add Opset 13 support to Split
> Fix Split shape issue and add Opset 13 support to it

- .travis/setup_onnx_target.sh
- doc/support_status.md
- onnx_tf/handlers/backend/max_pool.py
- onnx_tf/handlers/backend/mod.py
- onnx_tf/handlers/backend/resize.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
- test/backend/test_onnx_backend.py
This should address issue #591 and #601
> Add Opset 11 support for Resize

- onnx_tf/handlers/backend/split_to_sequence.py
- test/backend/test_model.py
Add SplitToSequence Support for Opset 11
> Add SplitToSequence Support for Opset 11

- onnx_tf/handlers/backend/tfidf_vectorizer.py
The tfidf vectorizer handler has a map_fn with string constant
that doesn't work on gpu only. It is a known issue in Tensorflow.
This PR is to provide a temporary fix by placing the map_fn
specifically on cpu. Once the TF bug is fixed, we can remove
the fix.
> Fix map_fn with string issue on gpu

- onnx_tf/handlers/backend/non_max_suppression.py
Input max_output_boxes_per_class, iou_threshold and score_threshold
should all be scalar, but the handler will accept 1-D 1 element tensor
as the value and squeeze out the extra dimension.
(The unit tests in ONNX backend test are using 1-D 1 element tensor for
max_output_boxes_per_class, iou_threshold and score_threshold however,
most models use scalar for those inputs.)
> Fix NonMaxSuppression handler on tf-1.x branch

- doc/support_status.md
- onnx_tf/handlers/backend/dynamic_quantize_linear.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
- test/backend/test_onnx_backend.py
> Add opset 11 support for DynamicQuantizeLinear in tf-1.x

- doc/support_status.md
- onnx_tf/handlers/backend/clip.py
- onnx_tf/handlers/backend/conv_integer.py
- onnx_tf/handlers/backend/mat_mul_integer.py
- onnx_tf/handlers/backend/q_linear_conv.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
1. Fix Clip optinal inputs handle and add Opset 12 support
2. Fix ConvInteger optional inputs handle
3. Fix MatMulInteger optional inputs handle
4. Fix how QLinearConv apply bias
> Fix optional inputs handle for Ops on tf-1.x

- onnx_tf/handlers/backend/resize.py
- test/backend/test_node.py
> Fix Resize handler

- doc/support_status.md
- onnx_tf/handlers/backend/gather_elements.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
> Add opset 11 support for GatherElements (tf-1.x)

- onnx_tf/handlers/backend/batch_normalization.py
- onnx_tf/handlers/backend/conv_mixin.py
- onnx_tf/handlers/backend/upsample.py
- test/backend/test_dynamic_shape.py
- test/backend/test_node.py
1. Fix dynamic batch size issue seen in #683 for ConvTranspose
2. Fix dynamic input issue seen in #688 for BatchNormalization
> Add dynamic shape support to ConvTranspose and BatchNormalization

- test/backend/test_dynamic_shape.py
- test/backend/test_node.py
> Moved onnx imports before tensorflow

- onnx_tf/handlers/backend/conv_mixin.py
- onnx_tf/handlers/backend/expand.py
- onnx_tf/handlers/backend/tfidf_vectorizer.py
- test/backend/test_node.py
This PR backports two operator fixes into tf-1.x branch
1. Fix conv transpose shape calculation, PR 622
2. Fix expand issue with boolean, PR 602
> Backport operator fixes into tf-1.x branch

- onnx_tf/handlers/backend/batch_normalization.py
- onnx_tf/handlers/backend/conv_mixin.py
- onnx_tf/handlers/backend/upsample.py
- test/backend/test_dynamic_shape.py
- test/backend/test_node.py
1. Backport dynamic shape support for ConvTranspose and BatchNormalization(PR #687) to tf-1.x branch
2. Backport ConvTranspose testcases (PR #594) to tf-1.x branch
> Backport dynamic shape support to tf-1.x branch

- onnx_tf/handlers/backend/celu.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
> Add Celu support for opset 12

- doc/support_status.md
- onnx_tf/handlers/backend/gather_and_scatter_mixin.py
- onnx_tf/handlers/backend/gather_nd.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
1. send in batch_dims attribute
2. update check out-of-bound indices function to support batch_dims
3. verify tf.gather_nd support bfloat16 as data-in and data-out
> Add opset 12 and 13 support for GatherND

- .gitignore
- doc/support_status.md
- onnx_tf/common/__init__.py
- onnx_tf/common/data_type.py
- onnx_tf/common/exception.py
- onnx_tf/handlers/backend/resize.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
1. Add Resize Opset 13 support
2. Use user defined auto cast flag for casting unsupported datatype in tf.resize
> Add Resize Opset 13 support

- onnx_tf/backend_tf_module.py
1. Create initializer_dict in BackendTFModule.__init__
2. Use initializer_dict in BackendTFModule.gen_tensor_dict and BackendTFModule.__call__
> Create initializer_dictionary in BackendTFModule.__init__

- onnx_tf/backend.py
- onnx_tf/backend_tf_module.py
- onnx_tf/common/__init__.py
- onnx_tf/common/exception.py
- onnx_tf/handlers/backend/non_max_suppression.py
- onnx_tf/handlers/backend_handler.py
- test/backend/test_dynamic_shape.py
1. Create unique handlers' variable name by adding node.name to it.
If cannot create unique variable name with node.name then throw
exception.
2. Allow handler to set the variable shape base on node.attrs values
3. Move TFModule class from backend.run_node to backend_tf_module.py
4. Create handlers' variables in TFModule.init
> Modify handlers' variables creation process

- .travis.yml
> Update package dependency versions for TravisCI

- doc/support_status.md
- onnx_tf/handlers/backend/roi_align.py
Hi
This repo add roi_align support to TF2.x, same logic as https://github.com/onnx/onnx-tensorflow/pull/789
I am new to TF2.x, hope this works fine.
> add roi_align support to tf2.x

- onnx_tf/backend_tf_module.py
- onnx_tf/common/exception.py
- onnx_tf/handlers/backend/if.py
- onnx_tf/handlers/backend/loop.py
- onnx_tf/handlers/backend/non_max_suppression.py
- onnx_tf/handlers/backend/scan.py
- onnx_tf/handlers/backend_handler.py
Move create_variables and get_initializer code into handlers
> Update handlers' variables creation process

- doc/support_status.md
- onnx_tf/handlers/backend/relu.py
- onnx_tf/opset_version.py
1. add opset 13 support for Relu to close issue #811
> Add Opset 13 support for Relu

- onnx_tf/handlers/backend/slice.py
Backport slice dynamic shape support (PR #776)
> Backport slice dynamic shape support

- onnx_tf/common/__init__.py
- onnx_tf/common/data_type.py
- onnx_tf/common/exception.py
- onnx_tf/handlers/backend/resize.py
- test/backend/test_node.py
1. Backport Resize fix (PR #702)
2. Backport Resize auto-cast support (PR #731)
> Backport Resize handler fix to tf-1.x branch

- README.md
Update readme production install instructions since the
latest package is uploaded and available for pip install.
> Update readme production install

- onnx_tf/handlers/backend/clip.py
- onnx_tf/handlers/backend/sign.py
Fix auto cast checking for clip and sign handlers so
the user option will be properly applied
> Fix auto cast checking for clip and sign

- doc/support_status.md
- onnx_tf/handlers/backend/onehot.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
Backport PR #799 to tf-1.x branch
> Baskport auto-cast capability to Onehot in tf-1.x branch

- doc/support_status.md
- onnx_tf/handlers/backend/dropout.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
- test/backend/test_onnx_backend.py
Backport PR #671 and #774 to tf-1.x branch
> Backport Dropout Opset 12 support to tf-1.x branch

- doc/support_status.md
- onnx_tf/handlers/backend/concat_from_sequence.py
- onnx_tf/handlers/backend/split_to_sequence.py
- onnx_tf/opset_version.py
- test/backend/test_model.py
- test/backend/test_onnx_backend.py
Backport ConcatFromSequence and SplitToSequence ops
> Backport ConcatFromSequence and SplitToSequence ops

- .github/workflows/test-backend.yml
Allow failure for the latest ONNX and TF in CI
> Allow failure for the latest ONNX and TF in CI

- onnx_tf/handlers/backend/mod.py
- test/backend/test_model.py
Fix CI test errors introduced by TF 2.4.0 including
lstm: test_model.py
gru: test_model.py
rnn: test_model.py
mod: mod.py
> Fix CI test errors introduced by TF 2.4.0

- test/test_modelzoo.py
Updated test_modelzoo.py to run all models with the provided test data in model zoo
> Run all models in modelzoo with sample test data

- onnx_tf/handlers/backend/conv_mixin.py
This will try to convert to DepthwiseConv with condition of group value.
- based on https://github.com/onnx/onnx-tensorflow/issues/470#issuecomment-681584457 by CyanHillFox@github
Signed-off-by: SaeHie Park <saehie.park@samsung.com>
> Fix Conv2D for case of group for DepthwiseConv

- doc/support_status.md
- onnx_tf/handlers/backend/cumsum.py
- onnx_tf/opset_version.py
Add support for Cumsum opset 14, which introduced two more
data types for input.
> Add support for Cumsum opset 14

- onnx_tf/handlers/backend/conv_mixin.py
Fix depthwise condition check with unknown input shape for conv
where x_shape[1] could be a tensor and group == x_shape[1] will
be always False.
> Fix depthwise condition check with unknown input shape

- example/train_onnx_model.py
- onnx_tf/handlers/backend/batch_normalization.py
Update batch normalization  handler to support training 
Update training example:
1. training tf model before save to to onnx model
2. add vgg model to test larger mode performance
3. remove optimizer op run when do test
4. use all test data to run trained onnx model
> Support training with batch normalization op; update training example

- onnx_tf/handlers/backend/conv_mixin.py
Fix depthwise condition bug, as described in issue https://github.com/onnx/onnx-tensorflow/issues/902
> Fix depthwise condition bug

- onnx_tf/backend_rep.py
- onnx_tf/backend_tf_module.py
- test/backend/test_dynamic_shape.py
- test/backend/test_model.py
Fix output names issue https://github.com/onnx/onnx-tensorflow/issues/898
> Fix output names issue

- Versioning.md
Add version 1.8.0 to Versioning.md
> Add version 1.8.0 to Versioning.md

- onnx_tf/backend_rep.py
- onnx_tf/backend_tf_module.py
Fix unknown output shape for export as reported in issue
https://github.com/onnx/onnx-tensorflow/issues/913.
> Fix unknown output shape for export

- doc/support_status.md
- onnx_tf/handlers/backend/multinomial.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
Add support for Multinomial as requested as part of issue
https://github.com/onnx/onnx-tensorflow/issues/728
> Add support for Multinomial

- doc/support_status.md
- onnx_tf/handlers/backend/trilu.py
- onnx_tf/opset_version.py
- test/backend/test_dynamic_shape.py
New onnx operator https://github.com/onnx/onnx/pull/3291
> Add new operator Trilu

- onnx_tf/gen_opset.py
> support generate opset for custom op/domain

- onnx_tf/backend.py
- onnx_tf/backend_rep.py
- onnx_tf/handlers/backend/identity.py
- onnx_tf/opset_version.py
- test/backend/test_node.py
- test/backend/test_onnx_backend.py
> support sequence type; support opset 14 of identity op

- doc/support_status.md
- onnx_tf/handlers/backend/batch_normalization.py
- onnx_tf/opset_version.py
- test/backend/test_onnx_backend.py
Partially support BatchNormalization opset 14, where the new
training_mode attribute is not 1
> Partially support BatchNormalization opset 14

- doc/support_status.md
- onnx_tf/handlers/backend/castlike.py
- onnx_tf/opset_version.py
> support castlike opset 15

- .github/workflows/test-backend.yml
- .github/workflows/test-modelzoo.yml
- README.md
- doc/support_status.md
- onnx_tf/handlers/backend/bernoulli.py
- onnx_tf/opset_version.py
- test/backend/test_onnx_backend.py
This operator is non-deterministic and may not produce the same values so we still need to exlucde the test case.
> support bernoulli opset 15

- .github/workflows/test-modelzoo.yml
Update Tensorflow Version for Modelzoo Test
> Update Tensorflow Version for Modelzoo Test

- README.md
Add project clarification to README to address issue https://github.com/onnx/onnx-tensorflow/issues/1010
> Add project clarification to README

- onnx_tf/backend.py
Fix string comparison in validate_initializer_name
> Fix string comparison
